### ISSUE TITLE
gives traceback

### ISSUE THREAD

**Issue by coderadam2000** [DinosuGithub/Shared-Piano-MIDI-Saver#2]
it says line 58 in saving.py `"elapsed": max([note['end'] for note in self.notes]) + 10` ValueError: max() iterable argument is empty
pls help

**Comment by DinosuGithub** [comment]
Could you please send the link to the MIDI file you used?

**Comment by coderadam2000** [comment]
how?

**Comment by coderadam2000** [comment]
oops

**Comment by coderadam2000** [comment]
fix that

**Comment by coderadam2000** [comment]
https://midishare.dev/detail/d2aec47e6b36ddb171b5fc3297c754c2

**Comment by DinosuGithub** [comment]
Ah, I found the issue. It had to do with the fact that not all MIDI files use note_off messages. Thanks for letting me know.
